import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./component/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "./component/Footer";



export const metadata: Metadata = {
  title: "Shop Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
      <body className="bg-gray-50 text-gray-900">
    
        <header className="container mx-auto p-3">
          <Navbar />
        </header>


        <main className="container mx-auto p-3 min-h-[70vh]">
          <Toaster />
          {children}
        </main>

       
        <footer className="container mx-auto p-3">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
